"CREATE TABLE User (
 		`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
		name VARCHAR(30) NOT NULL,
		password VARCHAR(30) NOT NULL,
		reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  		PRIMARY KEY (`id`)
		)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0";
